export const jobs = [
    {
      id: 'job1',
      title: 'Senior Frontend Developer',
      company: 'TechCorp',
      logo: '/images/companies/techcorp.svg',
      location: 'San Francisco, CA',
      type: 'Full-time',
      salary: '$120K - $150K',
      postedDate: '2 days ago',
      experienceLevel: 'Senior Level',
      category: 'software-development',
      featured: true,
      description: 'We are looking for an experienced Frontend Developer to join our team and help build amazing user experiences.',
      skills: ['React', 'TypeScript', 'CSS', 'Next.js']
    },
    {
      id: 'job2',
      title: 'Product Designer',
      company: 'DesignHub',
      logo: '/images/companies/designhub.svg',
      location: 'Remote',
      type: 'Full-time',
      salary: '$90K - $120K',
      postedDate: '1 day ago',
      experienceLevel: 'Mid Level',
      category: 'design',
      featured: true,
      description: 'Join our design team to create beautiful and functional interfaces for our clients.',
      skills: ['Figma', 'UI/UX', 'Prototyping', 'User Research']
    },
    {
      id: 'job3',
      title: 'DevOps Engineer',
      company: 'CloudSystems',
      logo: '/images/companies/cloudsystems.svg',
      location: 'New York, NY',
      type: 'Full-time',
      salary: '$130K - $160K',
      postedDate: '3 days ago',
      experienceLevel: 'Senior Level',
      category: 'software-development',
      featured: true,
      description: 'Help us build and maintain our cloud infrastructure and deployment pipelines.',
      skills: ['AWS', 'Kubernetes', 'Docker', 'CI/CD']
    },
    {
      id: 'job4',
      title: 'Marketing Manager',
      company: 'GrowthLabs',
      logo: '/images/companies/growthlabs.svg',
      location: 'Chicago, IL',
      type: 'Full-time',
      salary: '$85K - $110K',
      postedDate: '1 week ago',
      experienceLevel: 'Mid Level',
      category: 'marketing',
      featured: true,
      description: 'Lead our marketing efforts to drive growth and brand awareness.',
      skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics']
    },
    {
      id: 'job5',
      title: 'Backend Developer',
      company: 'DataFlow',
      logo: '/images/companies/dataflow.svg',
      location: 'Remote',
      type: 'Full-time',
      salary: '$110K - $140K',
      postedDate: '5 days ago',
      experienceLevel: 'Mid Level',
      category: 'software-development',
      featured: true,
      description: 'Build robust and scalable backend systems for our data processing platform.',
      skills: ['Node.js', 'Python', 'PostgreSQL', 'API Design']
    },
    {
      id: 'job6',
      title: 'UX Researcher',
      company: 'UserFirst',
      logo: '/images/companies/userfirst.svg',
      location: 'Seattle, WA',
      type: 'Full-time',
      salary: '$95K - $125K',
      postedDate: '2 days ago',
      experienceLevel: 'Mid Level',
      category: 'design',
      featured: true,
      description: 'Conduct user research to inform our product design decisions.',
      skills: ['User Testing', 'Interviews', 'Data Analysis', 'Prototyping']
    },
  ];